Лабораторная работа № 2.
Programming-Classrooms/practicalworks-VadimLabotsky pull request #2
Opened 2023-11-29 18:45 UTC by VadimLabotsky

## Pull Request лабораторной работы №2

### Условие лабораторной работы

< Написать программу, которая для заданного натурального числа:
5. вычисляет сумму первых чисел Фибоначчи, не превосходящую
заданного числа N;
2. удаляет из записи числа все цифры, кратные минимальной цифре;
Написать программу, которая
18. Находит в последовательности, состоящей из цифр подряд
записанных натуральных чисел, цифру с заданным номером.>

### Вопросы по условию

2023-12-10 13:38 UTC, AlexandrOsiptsov requested changes
camelCase, условия, логическое разделение

2023-12-10 13:38 UTC, AlexandrOsiptsov commented on laboratory-task-2/Laboratory work 2.1.cpp
> +using std::cin;
Так не делать. Мы в коде явно указываем, какие модули используются из стандартной библиотеки

2023-12-10 13:38 UTC, AlexandrOsiptsov commented on laboratory-task-2/Laboratory work 2.1.cpp
> +
Где условие задачи?

2023-12-10 13:38 UTC, AlexandrOsiptsov commented on laboratory-task-2/Laboratory work 2.2.cpp
> +#include <iostream>
Нет условия

2023-12-10 13:38 UTC, AlexandrOsiptsov commented on laboratory-task-2/Laboratory work 2.1.cpp
> +        number1 = number1 + number2;
У тебя есть операторы `+=` / `-=`

2023-12-10 13:38 UTC, AlexandrOsiptsov commented on laboratory-task-2/Laboratory work 2.1.cpp
> +        cout << number1 << '\t';
Вместо вывода знаков табуляции, используй `iomanip`

2023-12-10 13:38 UTC, AlexandrOsiptsov commented on laboratory-task-2/Laboratory work 2.2.cpp
> +using std::cin;
минус

2023-12-10 13:38 UTC, AlexandrOsiptsov commented on laboratory-task-2/Laboratory work 2.2.cpp
> +	int64_t number, min{ 9 }, last_number{ 0 };
минус

2023-12-10 13:38 UTC, AlexandrOsiptsov commented on laboratory-task-2/Laboratory work 2.2.cpp
> +	int64_t time_number;
Переменную нужно чем-то инициализировать

2023-12-10 13:38 UTC, AlexandrOsiptsov commented on laboratory-task-2/Laboratory work 2.2.cpp
> +	}
Логического разделения кода нет. Названия оформлены не в том стиле, в котором мы утверждали

2023-12-10 13:38 UTC, AlexandrOsiptsov commented on laboratory-task-2/Laboratory_work_2.3.cpp
> +#include <iostream>
Условие

2023-12-10 13:38 UTC, AlexandrOsiptsov commented on laboratory-task-2/Laboratory_work_2.3.cpp
> +}
По смыслу функция максимально правильная. Молодец, что сделал именно так. 
Но тело очень странное. У тебя есть функция `std::pow()`

2024-01-06 17:48 UTC, AlexandrOsiptsov requested changes
Вместе со второй лабой залита первая. Сделай коммит, который удаляет файл с первой лабой

2024-01-12 20:49 UTC, Voio77 requested changes
Всё видел

2024-06-17 16:22 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:42 UTC, merged