Лабораторная работа №4
Programming-Classrooms/practicalworks-VadimLabotsky pull request #4
Opened 2023-11-29 19:13 UTC by VadimLabotsky

## Pull Request лабораторной работы №4
### Условие лабораторной работы

<  При решении следующих задач использовать динамический массив. При
необходимости заполнения массива предусмотреть два способа: ввод с клавиатуры и
заполнение с помощью датчика случайных чисел. В последнем случае перед заполнением
массива ввести границы интервала, которому должны принадлежать элементы массива.
Вывести результаты расчетов. Если по каким-либо причинам решение задачи
невозможно, вывести соответствующее сообщение.
Вариант 5
В целочисленной прямоугольной матрице найти:
- произведение элементов в тех строках, которые не содержат отрицательных
элементов;
- переставить строки и столбцы матрицы так, чтобы в левом верхнем углу
матрицы оказался максимальный положительный элемент матрицы.>

### Вопросы по условию

2023-11-30 16:55 UTC, AlexandrOsiptsov requested changes
30 мест пометил. Есть над чем работать. + переведи все названия в camelCase

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +{
2 строки после подключения модулей

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +int32_t enter_row()
Подумай над более описательным названием функции

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +	while (a == false)
`a` уже является булевой переменной, нет нужды прописывать `== false`. Более красиво тут будет смотреться `while (!a)`

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +	bool a = false;
Название переменной не описывает её назначения

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +		}
К чему здесь пустое место в 17-ой строке?

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +		}
Пустое место в 22-ой строке.
Непонятное сообщение исключения

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +}
К чему столько пустых строк?

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +void  allocates_memory_for_a_two_dimensional_array(int64_t**& mtrx, const int32_t& row, const int32_t& column)
Переборщил с кол-вом слов в названии. Сократи, но так, чтобы всё ещё было понятно для чего нужна эта функция

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +	mtrx = new int64_t * [row];
Пишем чистый код, лучше убрать пробел между `int64_t` и `*`

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +			std::cout << "Enter elements massive ";
Сообщение не описывает действительности

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +			std::cout << '\t';
Используй `iomanip` в таких ситуациях

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +void fill_matrix_is_random(int64_t** mtrx, const int32_t& row, const int32_t& column, int32_t leftborder, int32_t rightborder)
Чуть промахнулся с переводом. Лучше что-то типа `mtrxFillRand`

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +			mtrx[i][j] = (leftborder + rand() % ((rightborder - leftborder + 1)));//������� �� 0 � 1
Сбитая кодировка

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +
Пустые строки

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +
Пустая строка

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +void output_mtrx(int64_t** mtrx, const int32_t& row, const int32_t& column)
output не всегда выполняется в консоль, есть разные потоки. Функции, выполняющие вывод в консоль, обычно называют `print`. В данном случае подойдёт `printMtrx`

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +void choice_enter_matrix(int64_t** mtrx, const int32_t row, const int32_t column, int32_t& leftborder, int32_t& rightborder)
Подумай над названием

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +bool check_no_negative_elements(std::int64_t** mtrx, const std::int32_t& fix_index, const std::int32_t& column) {
До этого ты использовал типы фиксированного размера без `std::`. Код должен быть подогнан под единый формат

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +void product_in_some_row(std::int64_t** mtrx, const std::int32_t& column, const std::int32_t& row)
Подумай над названием

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +
Пустая строка

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +int64_t  max_elements_in_matrix(int64_t**& mtrx, const int32_t& row, const int32_t& column, int32_t& column_max_elements_matrix, int32_t& row_max_elements_matrix) {
`int64_t**&`, не то, что ты имел ввиду. Смотри беседу

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +
Пустые строки

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +}
А вот в конце файла как раз принято оставлять пустую строку

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +
Пустые строки

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +
Пустая строка

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +
Пустая строка

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +void delete_matrix(int64_t**& mtrx, const int32_t& row, const int32_t& column)
Снова указатель по ссылке передаёшь

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +void swap_max_elements_in_column(int64_t**& mtrx, const int32_t& row, const int32_t& column, int32_t& column_max_elements_matrix)
Опять указатель по ссылке передал

2023-11-30 16:55 UTC, AlexandrOsiptsov commented on laboratory-task-4/Labotary_work_4.cpp
> +void swap_max_elements_in_row(int64_t**& mtrx, const int32_t& row, const int32_t& column, int32_t& row_max_elements_matrix)
Указатель по ссылке

2023-12-02 18:22 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +void delete_matrix(int64_t**& mtrx, const int32_t& row, const int32_t& column)
Данная функция чистит память у матрицу. Тут & нужен.

2023-12-03 15:14 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +{
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:15 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +int32_t enter_row()
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:16 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +	bool a = false;
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:16 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +		}
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:16 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +	}
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:16 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +}
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:17 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +void  allocates_memory_for_a_two_dimensional_array(int64_t**& mtrx, const int32_t& row, const int32_t& column)
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:17 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +	mtrx = new int64_t * [row];
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:17 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +void fill_matrix_is_random(int64_t** mtrx, const int32_t& row, const int32_t& column, int32_t leftborder, int32_t rightborder)
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:17 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:17 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:17 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +void output_mtrx(int64_t** mtrx, const int32_t& row, const int32_t& column)
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:18 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +bool check_no_negative_elements(std::int64_t** mtrx, const std::int32_t& fix_index, const std::int32_t& column) {
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:18 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +void product_in_some_row(std::int64_t** mtrx, const std::int32_t& column, const std::int32_t& row)
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:18 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +int64_t  max_elements_in_matrix(int64_t**& mtrx, const int32_t& row, const int32_t& column, int32_t& column_max_elements_matrix, int32_t& row_max_elements_matrix) {
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:18 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +}
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:19 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:19 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +void swap_max_elements_in_column(int64_t**& mtrx, const int32_t& row, const int32_t& column, int32_t& column_max_elements_matrix)
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-03 15:20 UTC, VadimLabotsky commented on laboratory-task-4/Labotary_work_4.cpp
> +void swap_max_elements_in_row(int64_t**& mtrx, const int32_t& row, const int32_t& column, int32_t& row_max_elements_matrix)
Исправил. 6f8c23c8e5effd528511f31115e7297e698e601c

2023-12-10 14:08 UTC, AlexandrOsiptsov requested changes
Также плохо, смотри на ревью предыдущей лабы, огрехи все те же

2023-12-10 14:08 UTC, AlexandrOsiptsov commented on laboratory-task-4/LabotaryWork4.cpp
> +#include<exception>
Плохо чистил

2023-12-10 14:08 UTC, AlexandrOsiptsov commented on laboratory-task-4/LabotaryWork4.cpp
> +		}
Бред. Подумай над тем, что здесь происходит

2023-12-10 14:08 UTC, AlexandrOsiptsov commented on laboratory-task-4/LabotaryWork4.cpp
> +void  allocatesMemoryForArray(int64_t**& mtrx,const int32_t& row, const int32_t& column)
Указатель на указатель по ссылке

2023-12-10 14:08 UTC, AlexandrOsiptsov commented on laboratory-task-4/LabotaryWork4.cpp
> +void  allocatesMemoryForArray(int64_t**& mtrx,const int32_t& row, const int32_t& column)
Что с названием? Ты открываешь память для матрицы, а не массива

2023-12-10 14:08 UTC, AlexandrOsiptsov commented on laboratory-task-4/LabotaryWork4.cpp
> +			std::cout << std::setw(4);
Понимаешь ли ты, что именно здесь происходит?

2023-12-10 14:08 UTC, AlexandrOsiptsov commented on laboratory-task-4/LabotaryWork4.cpp
> +}
Функция должна выполнять одно действие. Если ты считаешь специфическое произведение в строке, то посчитай и верни его из функции. А уже в main выводи разные сообщения

2023-12-10 14:08 UTC, AlexandrOsiptsov commented on laboratory-task-4/LabotaryWork4.cpp
> +		deleteMatrix(mtrx, row, column);
Из-за того, что ты пихал по функциям всё что нужно и не нужно, main стал похож на набор строк, а не логическую последовательность

2024-01-06 18:00 UTC, AlexandrOsiptsov requested changes
Просмотри комменты

2024-01-06 18:00 UTC, AlexandrOsiptsov commented on laboratory-task-4/main.cpp
> +}
Название

2024-06-17 16:21 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:40 UTC, merged